FROM fedora
MAINTAINER Berezhko Ivan <ivan@berezhko.ru>

RUN dnf -y update
RUN dnf install -y git texlive make inkscape latexmk dejavu-sans-mono-fonts linux-libertine-fonts texlive-ncctools texlive-newtx texlive-imakeidx texlive-idxlayout texlive-lettrine texlive-minifp linux-libertine-biolinum-fonts vim texlive-hyphen-russian
COPY build.sh /
ENTRYPOINT /build.sh
